#!/bin/bash

cat /etc/motd

cat <<EOF
Keyboard:

  Super + Q:  open foot terminal
  Super + R:  open rofi application launcher
  Super + V:  toggle floating
  Super + {0-9}:  change workspace
  Super + {arrow}: change focused window
  Super + C:  close current window

To install eweOS to your disk, check wiki first:

  https://os-wiki.ewe.moe

EOF

bash
